#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home : 
  path : /home
  controller : App\Controller\HomeController::homePage

user_sub : 
  path : /user
  controller : App\Controller\UserController::subscribe
  methods : POST